# Generated by Django 2.2.7 on 2019-11-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=50)),
                ('ingredient_name', models.CharField(max_length=50)),
                ('measurement_choice', models.CharField(max_length=200)),
                ('ingredient_quantity', models.IntegerField()),
                ('recipe_procedure', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
