# Generated by Django 2.2.7 on 2019-11-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrecipe', '0002_auto_20191124_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_procedure',
            field=models.TextField(),
        ),
    ]
